<?php
if (!extension_loaded("pthreads")) {
    define('PTHREADS_INHERIT_ALL',1118481);
    define('PTHREADS_INHERIT_NONE',0);
    define('PTHREADS_INHERIT_INI',1);
    define('PTHREADS_INHERIT_CONSTANTS',16);
    define('PTHREADS_INHERIT_CLASSES',4096);
    define('PTHREADS_INHERIT_FUNCTIONS',256);
    define('PTHREADS_INHERIT_INCLUDES',65536);
    define('PTHREADS_INHERIT_COMMENTS',1048576);
    define('PTHREADS_ALLOW_HEADERS',268435456);
}